"""Initial migration

Revision ID: c6cab1c6e19c
Revises: 
Create Date: 2024-02-01 10:01:59.618059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cab1c6e19c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hashed', sa.String(length=256), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('senha1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha1', sa.VARCHAR(length=150), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('senha_hashed')

    # ### end Alembic commands ###
